import { Question } from "@/lib/mbti/types";

const OPTIONS = ["非常同意", "比较同意", "比较不同意", "非常不同意"];

export const questions: Question[] = [
  { id: "q001", text: "在陌生局里，我通常会先开口找话题。", dimension: "EI", direction: "forward", options: OPTIONS },
  { id: "q002", text: "连续社交几个小时后，我反而更兴奋。", dimension: "EI", direction: "forward", options: OPTIONS },
  { id: "q003", text: "我更喜欢边聊边想，而不是想好再说。", dimension: "EI", direction: "forward", options: OPTIONS },
  { id: "q004", text: "参加活动时，我会自然地认识新朋友。", dimension: "EI", direction: "forward", options: OPTIONS },
  { id: "q005", text: "我愿意在群里直接抛观点，哪怕还不成熟。", dimension: "EI", direction: "forward", options: OPTIONS },
  { id: "q006", text: "我常常是饭局里把气氛炒热的人。", dimension: "EI", direction: "forward", options: OPTIONS },
  { id: "q007", text: "遇到问题时，我倾向先找人聊聊再行动。", dimension: "EI", direction: "forward", options: OPTIONS },
  { id: "q008", text: "比起一个人琢磨，我更喜欢团队碰撞。", dimension: "EI", direction: "forward", options: OPTIONS },
  { id: "q009", text: "周末独处一天，会让我状态回满。", dimension: "EI", direction: "reverse", options: OPTIONS },
  { id: "q010", text: "在开口前，我通常会在脑内排练一遍。", dimension: "EI", direction: "reverse", options: OPTIONS },
  { id: "q011", text: "比起很多泛泛之交，我更重视少数深交。", dimension: "EI", direction: "reverse", options: OPTIONS },
  { id: "q012", text: "大型聚会结束后，我通常需要独处缓一缓。", dimension: "EI", direction: "reverse", options: OPTIONS },
  { id: "q013", text: "我更喜欢安静环境，不太爱高密度社交。", dimension: "EI", direction: "reverse", options: OPTIONS },
  { id: "q014", text: "遇到情绪低落时，我先自己消化而不是立刻倾诉。", dimension: "EI", direction: "reverse", options: OPTIONS },
  { id: "q015", text: "我常被说看起来有点高冷，其实只是慢热。", dimension: "EI", direction: "reverse", options: OPTIONS },
  { id: "q016", text: "比起即兴社交，我更享受有准备的交流。", dimension: "EI", direction: "reverse", options: OPTIONS },

  { id: "q017", text: "我做决定时，通常先看可执行细节。", dimension: "SN", direction: "forward", options: OPTIONS },
  { id: "q018", text: "我记得住具体事实，比抽象概念更快。", dimension: "SN", direction: "forward", options: OPTIONS },
  { id: "q019", text: "我更信实测有效，而不是听起来很酷。", dimension: "SN", direction: "forward", options: OPTIONS },
  { id: "q020", text: "做事前我会先确认流程、资源和边界。", dimension: "SN", direction: "forward", options: OPTIONS },
  { id: "q021", text: "我更容易注意到当下环境的变化。", dimension: "SN", direction: "forward", options: OPTIONS },
  { id: "q022", text: "相比未来可能，我更关注现在能做什么。", dimension: "SN", direction: "forward", options: OPTIONS },
  { id: "q023", text: "我偏好明确说明书，不太爱猜谜式沟通。", dimension: "SN", direction: "forward", options: OPTIONS },
  { id: "q024", text: "买东西时，我会先对比参数和性价比。", dimension: "SN", direction: "forward", options: OPTIONS },
  { id: "q025", text: "我经常脑补如果这样会不会更有意思。", dimension: "SN", direction: "reverse", options: OPTIONS },
  { id: "q026", text: "我喜欢从一个点联想到很多可能性。", dimension: "SN", direction: "reverse", options: OPTIONS },
  { id: "q027", text: "比起按旧路径走，我更想试试新思路。", dimension: "SN", direction: "reverse", options: OPTIONS },
  { id: "q028", text: "我常被说点子很多，像脑洞永动机。", dimension: "SN", direction: "reverse", options: OPTIONS },
  { id: "q029", text: "我更在意趋势和模式，而不只是单点数据。", dimension: "SN", direction: "reverse", options: OPTIONS },
  { id: "q030", text: "抽象话题会让我兴奋，比如意义和愿景。", dimension: "SN", direction: "reverse", options: OPTIONS },
  { id: "q031", text: "我会先想为什么，再想怎么做。", dimension: "SN", direction: "reverse", options: OPTIONS },
  { id: "q032", text: "我愿意为一个好想法容忍前期不确定。", dimension: "SN", direction: "reverse", options: OPTIONS },

  { id: "q033", text: "判断对错时，我更看逻辑是否自洽。", dimension: "TF", direction: "forward", options: OPTIONS },
  { id: "q034", text: "讨论问题时，我会直接指出漏洞。", dimension: "TF", direction: "forward", options: OPTIONS },
  { id: "q035", text: "做决定时，我会优先考虑效率和结果。", dimension: "TF", direction: "forward", options: OPTIONS },
  { id: "q036", text: "就算关系很好，我也会坚持原则。", dimension: "TF", direction: "forward", options: OPTIONS },
  { id: "q037", text: "我不太怕冲突，前提是问题能讲清楚。", dimension: "TF", direction: "forward", options: OPTIONS },
  { id: "q038", text: "我欣赏有理有据，胜过我觉得。", dimension: "TF", direction: "forward", options: OPTIONS },
  { id: "q039", text: "我能把情绪和决策短暂分开处理。", dimension: "TF", direction: "forward", options: OPTIONS },
  { id: "q040", text: "我更愿意做正确但不讨好的选择。", dimension: "TF", direction: "forward", options: OPTIONS },
  { id: "q041", text: "我会先感受他人的情绪，再讨论方案。", dimension: "TF", direction: "reverse", options: OPTIONS },
  { id: "q042", text: "我不喜欢太生硬的表达方式。", dimension: "TF", direction: "reverse", options: OPTIONS },
  { id: "q043", text: "如果有人受伤，我会优先照顾关系。", dimension: "TF", direction: "reverse", options: OPTIONS },
  { id: "q044", text: "我更看重这件事是否对人友好。", dimension: "TF", direction: "reverse", options: OPTIONS },
  { id: "q045", text: "我常能觉察到别人没说出口的情绪。", dimension: "TF", direction: "reverse", options: OPTIONS },
  { id: "q046", text: "做决定时，我会考虑价值观是否一致。", dimension: "TF", direction: "reverse", options: OPTIONS },
  { id: "q047", text: "我宁愿慢一点，也不想让人难堪。", dimension: "TF", direction: "reverse", options: OPTIONS },
  { id: "q048", text: "在团队里，我常担任气氛修复师。", dimension: "TF", direction: "reverse", options: OPTIONS },

  { id: "q049", text: "我喜欢把计划提前排好，心里才踏实。", dimension: "JP", direction: "forward", options: OPTIONS },
  { id: "q050", text: "待办事项打勾，会让我很有成就感。", dimension: "JP", direction: "forward", options: OPTIONS },
  { id: "q051", text: "我不太喜欢临时变更，容易打乱节奏。", dimension: "JP", direction: "forward", options: OPTIONS },
  { id: "q052", text: "我倾向先定规则，再开始执行。", dimension: "JP", direction: "forward", options: OPTIONS },
  { id: "q053", text: "我会尽量把事情做完，而不是先放着。", dimension: "JP", direction: "forward", options: OPTIONS },
  { id: "q054", text: "按时交付对我来说是底线之一。", dimension: "JP", direction: "forward", options: OPTIONS },
  { id: "q055", text: "旅行前我会先看路线、预算和备选方案。", dimension: "JP", direction: "forward", options: OPTIONS },
  { id: "q056", text: "我倾向做有结论的会议，而不是漫聊。", dimension: "JP", direction: "forward", options: OPTIONS },
  { id: "q057", text: "我更喜欢保留弹性，计划可以边走边改。", dimension: "JP", direction: "reverse", options: OPTIONS },
  { id: "q058", text: "我常在截止前冲刺，效率反而更高。", dimension: "JP", direction: "reverse", options: OPTIONS },
  { id: "q059", text: "突发灵感来了，我会临时换路径。", dimension: "JP", direction: "reverse", options: OPTIONS },
  { id: "q060", text: "我不喜欢把未来安排得太死。", dimension: "JP", direction: "reverse", options: OPTIONS },
  { id: "q061", text: "我享受走到哪算哪的探索感。", dimension: "JP", direction: "reverse", options: OPTIONS },
  { id: "q062", text: "对我来说，选择太早会限制可能性。", dimension: "JP", direction: "reverse", options: OPTIONS },
  { id: "q063", text: "我更愿意先开工，再在过程中优化。", dimension: "JP", direction: "reverse", options: OPTIONS },
  { id: "q064", text: "我能适应变化，甚至有点享受变化。", dimension: "JP", direction: "reverse", options: OPTIONS }
];
